# To change this template, choose Tools | Templates
# and open the template in the editor.


-7001=ILLEGAL_ARGUMENT_EXCEPTION
-7002=ILLEGAL_STATE_EXCEPTION
-7003=TRANSACTION_REQUIRED_EXCEPTION
-7004=ENTITY_EXISTS_EXCEPTION
-7005=PERSISTENCE_EXCEPTION
-7006=ENTITY_NOT_FOUND_EXCEPTION
-7007=LOCK_TIMEOUT_EXCEPTION
-7008=PESSIMISTIC_LOCK_EXCEPTION
-7009=QUERY_TIMEOUT_EXCEPTION
-7010=No se encontraron resultados
-7011=NON_UNIQUE_RESULT_EXCEPTION
-7203=Error al consultar en la base de datos
-7204=Error en el m\u00e9todo que realiza la consulta
-7205=Error en el sistema
-7012=
-7401=Usuario inv\u00e1lido
-7402=Terminal inv\u00e1lida
-7403=Funcionario inv\u00e1lido
-7404=Usuario no se encuentra asociado
-7501=No se puede realizar la actualizaci\u00f3n
-7502=Documento no puede ser actualizado
-7503=Documento actualizado por otro
-7504=Error al ejecutar el procedimiento
-7505=Objeto se encuentra nulo

