error.-5001=Ha ocurrido un error obteniendo los elementos de un perfil.
error.-5002=Ha sucedido un error obtiendo las opciones a las cuales tiene permiso el usuario.
error.-5003=Ha ocurrido un error encontrando el elemento indicado.
error.-5004=Ha ocurrido un error encontrando el sistema indicado.
error.-5005=Ha ocurrido un error obteniendo el listado de Menu Padres.
error.-5006=Ha ocurrido un error listando el menu.
error.-5007=Ha ocurrido un error obteniendo el menu.
error.-5008=Ha ocurrido un error guardando el menu.
error.-5009=Ha ocurrido un error actualizando el menu.
error.-5010=Ha ocurrido un error eliminando el menu.
error.-5011=Ha ocurrido un error obtiendo el numero de ordenamiento
error.-5012=Ha ocurrido un error obteniendo el listado de acciones.
# SAVE_EXCEPTION
error.-5001=Ha ocurrido un error guardando {0}
# UPDATE_EXCEPTION
error.-5002=Ha ocurrido un error editando {0}
# DELETE_EXCEPTION
error.-5003=Ha ocurrido un error editando {0}
# FINDER_EXCEPTION
error.-5004=Ha ocurrido un error obteniendo {0}
# FINDER_LIST_EXCEPTION
error.-5005=Ha ocurrido un error obteniendo el listado de {0}

error.-5014=.
# USUARIO_INFO_EXCEPTION
error.-5020=Ha ocurrido un error consultando la informacion del usuario.
# USUARIO_LISTADO_EXCEPTION
error.-5021=Ha ocurrido un error obteniendo el listado de usuarios.
# USUARIO_CANTIDAD_EXCEPTION
error.-5022=Ha ocurrido un error obteniendo la cantidad de usuarios.
# USUARIO_SISTEMA_INFO_EXCEPTION
error.-5023=Ha ocurrido un error consultando la informacion del usuario sistema.
# 

# USUARIO_LISTADO_EXCEPTION
error.-5030=Ha ocurrido un error obteniendo el listado de funcionarios.

error.-5024=Ha ocurrido un error obteniendo el funcionario del partido.

